export const LOCK_HANGER = 'LOCK_HANGER'
export const CHANGE_LOOK = 'CHANGE_LOOK'
export const MAKE_STATE = 'MAKE_STATE'
export const CHANGE_LOOKS = 'CHANGE_LOOKS'
export const GIVE_LIKE = 'GIVE_LIKE'
export const CANCLE_LIKE = 'CANCLE_LIKE'
export const NAVI_TURN = 'NAVI_TURN'