# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy:
        matrix:
          node-version: [12.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies   # 의존 파일 설치
        working-directory: ./looks
        run: npm install
        
      - name: Update Dependencies   # 의존 파일 설치
        working-directory: ./looks
        run: sudo npm install -g react-scripts

      - name: Build                   # React Build
        working-directory: ./looks
        run: npm run build
